### PR TITLE
Update db column

### PR DESCRIPTION
**Pull request by balamark**
Use db column 'note' to indicate source of candidate so that we can filter out outdated data.
@terry77228: Can you add the logic to front end code to show only candidates merged from ballotpedia? I filled 'ballopedia' in candidates table column 'note' for this.

### CODE REVIEW

**Comment by soarhevn** [comment]
Mark, looks like there are conflicts. Can you check please.

**Comment by balamark** [comment]
can someone double check for me everything work as expected? I just merged my branch to master

**Comment by soarhevn** [comment]
Hopefully Tung-Tung can. :) Thanks

**Comment by terry77228** [comment]
I didn't see any guy has ballopedia in note column. Do I need to do something for it?

**Comment by balamark** [comment]
In the latest pull request :)

**Pull request closed without merging**
